import { IGiftOptions } from "./giftoptions.model";
import { IImageEntity } from "./imageentity.model";
import { IItemAttributes } from "./itemattributes.model";
import { IWalmartOpenApiBaseResponse } from "./walmartOpenApiBaseResponse.model";

export interface IItem extends IWalmartOpenApiBaseResponse {
  itemId: number;
  parentItemId: number;
  name: string;
  msrp: number;
  salePrice: number;
  upc: string;
  categoryPath: string;
  categoryNode: string;
  shortDescription: string;
  longDescription: string;
  brandName: string;
  thumbnailImage: string;
  mediumImage: string;
  largeImage: string;
  productTrackingUrl: string;
  ninetySevenCentShipping: boolean;
  standardShipRate: number;
  twoThreeDayShippingRate: number;
  size: string;
  color: string;
  marketplace: boolean;
  sellerInfo: string;
  shipToStore: boolean;
  freeShipToStore: boolean;
  modelNumber: string;
  productUrl: string;
  availableOnline: boolean;
  stock: string;
  customerRating: string;
  customerRatingImage: string;
  numReviews: number;
  clearance: boolean;
  preOrder: boolean;
  preOrderShipsOn?: Date;
  offerType: string;
  rhid: string;
  bundle: boolean;
  attributes: IItemAttributes;
  addToCartUrl: string;
  affiliateAddToCartUrl: string;
  freeShippingOver35Dollars: boolean;
  gender: string;
  age: number;
  imageEntities: IImageEntity[];
  isTwoDayShippingEligible: boolean;
  giftOptions: IGiftOptions;
}
